#define TECLA_SHIFT_DERECHO  0x85
#define TECLA_ALT_DERECHO    0x86
#define TECLA_GUI_DERECHO    0x87
#define TECLA_FLECHA_ARRIBA  0xDA
#define TECLA_FLECHA_ABAJO   0xD9
#define TECLA_FLECHA_IZQUIERDA 0xD8
#define TECLA_FLECHA_DERECHA 0xD7
#define TECLA_RETROCESO      0xB2
#define TECLA_TAB            0xB3
#define TECLA_RETORNO        0xB0
#define TECLA_ESC            0xB1
#define TECLA_INSERTAR       0xD1
#define TECLA_SUPRIMIR       0xD4
#define TECLA_AV_PAGINA      0xD3
#define TECLA_REP_PAGINA     0xD6
#define TECLA_INICIO         0xD2
#define TECLA_FIN            0xD5
#define TECLA_BLOQ_MAYUS     0xC1
#define TECLA_F1             0xC2
#define TECLA_F2             0xC3
#define TECLA_F3             0xC4
#define TECLA_F4             0xC5
#define TECLA_F5             0xC6
#define TECLA_F6             0xC7
#define TECLA_F7             0xC8
#define TECLA_F8             0xC9
#define TECLA_F9             0xCA
#define TECLA_F10            0xCB
#define TECLA_F11            0xCC
#define TECLA_F12            0xCD
#define TECLA_CTRL_IZQUIERDO 0x80
